---
apiVersion: v1
kind: Service
metadata:
  name: testapp-insecure
  namespace: testapp-insecure
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: testapp-insecure
  externalIPs:
    - 172.17.0.90
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp-insecure
  name: testapp-insecure
  namespace: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-insecure
  template:
    metadata:
      labels:
        app: testapp-insecure
    spec:
      containers:
      - image: cyberark/demo-app
        imagePullPolicy: IfNotPresent
        name: testapp-insecure
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: postgresql://testapp-db.testapp.svc.cluster.local:5432/postgres
          - name: DB_USERNAME
            value: test_app
          - name: DB_PASSWORD
            value: 5b3e5f75cb3cdc725fe40318
