apiVersion: v1
kind: Service
metadata:
  name: testapp-insecure
  labels:
    app: testapp-insecure
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: testapp-insecure
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp-insecure
  name: testapp-insecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp-insecure
  template:
    metadata:
      labels:
        app: testapp-insecure
    spec:
      containers:
      - image: docker pull cyberark/demo-app
        imagePullPolicy: IfNotPresent
        name: testapp-insecure
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: postgresql://testapp-db.testapp.svc.cluster.local:5432/postgres
          - name: DB_USERNAME
            value: test_app
          - name: DB_PASSWORD
            value: 5b3e5f75cb3cdc725fe40318
