---
kind: Service
apiVersion: v1
metadata:
  name: testapp-db
  namespace: testapp-ns
spec:
  selector:
    app: testapp-db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: testapp-db
  labels:
    app: testapp-db
spec:
  serviceName: testapp-db
  selector:
    matchLabels:
      app: testapp-db
  template:
    metadata:
      labels:
        app: testapp-db
    spec:
      containers:
      - name: testapp-db
        image: testapp-db
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5432
